development: 
  cloud_name: 'douu1isrc'
  api_key: '353116689615118'
  api_secret: 'guBHBZSC3CXH7SiJy9UP6Flohx0'
  secure: true

production:
  cloud_name: 'douu1isrc'
  api_key: '353116689615118'
  api_secret: 'guBHBZSC3CXH7SiJy9UP6Flohx0'
  secure: true 
