require 'factory_bot_rails'

FactoryBot.create_list(:country, 20)
FactoryBot.create_list(:company, 20)
FactoryBot.create_list(:genre, 20)
FactoryBot.create_list(:language, 20)
FactoryBot.create_list(:movie, 20)
FactoryBot.create_list(:person, 20)
FactoryBot.create_list(:rating, 20)
FactoryBot.create_list(:permission, 1, :admin)
FactoryBot.create_list(:permission, 1, :redactor)
FactoryBot.create_list(:permission, 1, :reviewer)
FactoryBot.create_list(:user, 1, :admin)
FactoryBot.create_list(:user, 1, :redactor)
FactoryBot.create_list(:user, 1, :reviewer)
